INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('USER');

INSERT INTO USERS (EMAIL, CREATED_BY, LAST_MODIFIED_BY, PASSWORD, ENABLED) VALUES ('admin@disqo.com', 1, 1, '$2a$10$Amld1hwUgpo4XEvaXWmFcenpOBTsyqphiSsDY6ThqoWLaPZGOnwtq', '1');
INSERT INTO USERS (EMAIL, CREATED_BY, LAST_MODIFIED_BY, PASSWORD, ENABLED) VALUES ('alex@disqo.com', 1, 1, '$2a$10$8rFAPwx47JvkAXPq3LLU0eo0072Ck9mebB3Z7olFjqK6SoOH6Jx/i', '1');
INSERT INTO USERS (EMAIL, CREATED_BY, LAST_MODIFIED_BY, PASSWORD, ENABLED) VALUES ('alice@disqo.com', 1, 1, '$2a$10$2Ez/EOz3nDZBn3Lstk574umyEogWHtb8nvT92mNnMskRr9a6PJWja', '1');
INSERT INTO USERS (EMAIL, CREATED_BY, LAST_MODIFIED_BY, PASSWORD, ENABLED) VALUES ('john@disqo.com', 1, 1, '$2a$10$34UIEtoIWHYVpBPxxe5/ZOqBC.FSDWU3gqiAzFIFsPdV0hgOlFkQ6', '1');
INSERT INTO USERS (EMAIL, CREATED_BY, LAST_MODIFIED_BY, PASSWORD, ENABLED) VALUES ('louis@disqo.com', 1, 1, '$2a$10$CFIfovA54MlKKctCtggEeesG5HCK.u06NpJ1piEE4kz6mEdB73giq', '1');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (4, 2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (5, 2);

INSERT INTO NOTES (USER_ID, CREATED_BY, LAST_MODIFIED_BY, TITLE, CONTENT) VALUES (1, 1, 1, 'Admin Note', 'Admin note content');
INSERT INTO NOTES (USER_ID, CREATED_BY, LAST_MODIFIED_BY, TITLE, CONTENT) VALUES (2, 1, 1, 'Alex Note', 'Alex note content created by Admin');
INSERT INTO NOTES (USER_ID, CREATED_BY, LAST_MODIFIED_BY, TITLE, CONTENT) VALUES (3, 1, 1, 'Alice Note', 'Alice note content created by Admin');
INSERT INTO NOTES (USER_ID, CREATED_BY, LAST_MODIFIED_BY, TITLE, CONTENT) VALUES (4, 1, 1, 'John Note', 'John note content created by Admin');
INSERT INTO NOTES (USER_ID, CREATED_BY, LAST_MODIFIED_BY, TITLE, CONTENT) VALUES (5, 1, 1, 'Louis Note', 'Louis note content created by Admin');
