CREATE TABLE USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMAIL VARCHAR(20) NOT NULL UNIQUE,
  PASSWORD VARCHAR(60) NOT NULL,
  CREATED_BY INT,
  LAST_MODIFIED_BY INT,
  ENABLED TINYINT DEFAULT NULL,
  CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  VERSION INT,
  FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES USERS(ID)
);

CREATE TABLE ROLES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL
);

CREATE TABLE USERS_ROLES (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE NOTES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT,
  TITLE VARCHAR(50),
  CONTENT VARCHAR(1000),
  CREATED_BY INT,
  LAST_MODIFIED_BY INT,
  CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  VERSION INT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES USERS(ID)
);
